#!/bin/bash

clear
(cd /usr/bin && curl -sLko hg680p.sh https://raw.githubusercontent.com/hendramla/gpio-hg680p/main/hg680p.sh && chmod +x hg680p.sh)
(cd /usr/bin && curl -sLko inet-hg680p.sh https://raw.githubusercontent.com/hendramla/gpio-hg680p/main/inet-hg680p.sh && chmod +x inet-hg680p.sh)
echo " Install Selesai"
echo " Ketik Perintah: inet-hg680p.sh -r"
echo " Untuk Menyalakan LED Internet Indicator"
